name: Build JS SDK Package

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'packages/sdk/js/**'

jobs:
  build:
    name: Build SDK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        working-directory: ./packages/sdk/js/
        run: npm ci

      - name: Build package
        working-directory: ./packages/sdk/js/
        run: npm run build
