name: Build and Publish JS SDK Package

on:
  push:
    tags: [js-sdk-v*]

permissions:
  contents: write

jobs:
  publish:
    name: Build and publish SDK to NPM
    runs-on: ubuntu-20.04
    steps:
      - name: Execute pre-publish steps
        uses: ./.github/workflows/pre-publish-steps.yaml
      - name: Publish package
        run: npm publish --access=public
        working-directory: ./packages/sdk/js/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
